#ifndef VIDEOS_H
#define VIDEOS_H

#include <QString>
#include <utility>

static const int MAX_VIDEOS = 40;
using VideoPair = std::pair<int, QString>;
extern VideoPair videos[MAX_VIDEOS];

enum {
  VIDEO_1ST_CHARIOT,
  VIDEO_1ST_GLAD,
  VIDEO_ARMY_LOSE,
  VIDEO_ARMY_WIN,
  VIDEO_CITY_FIRE,
  VIDEO_CREDITS,
  VIDEO_EMMIGRATE,
  VIDEO_EMPIRE_CONTRACT,
  VIDEO_EMPIRE_EXPAND,
  VIDEO_EMP_2ND_CHANCE,
  VIDEO_EMP_ANGRY,
  VIDEO_EMP_DISPLEASED,
  VIDEO_EMP_SEND_ARMY,
  VIDEO_FESTIVAL1_FEAST,
  VIDEO_FESTIVAL2_CHARIOT,
  VIDEO_FESTIVAL3_GLAD,
  VIDEO_GLAD_REVOLT,
  VIDEO_GOD_CERES,
  VIDEO_GOD_MARS,
  VIDEO_GOD_MERCURY,
  VIDEO_GOD_NEPTUNE,
  VIDEO_GOD_VENUS,
  VIDEO_INTRO,
  VIDEO_LOGO,
  VIDEO_LOSE_GAME,
  VIDEO_MUGGING,
  VIDEO_POPULATION1,
  VIDEO_POPULATION2,
  VIDEO_POPULATION3,
  VIDEO_QUAKE,
  VIDEO_RIOT,
  VIDEO_SICK,
  VIDEO_SPY_ARMY,
  VIDEO_SPY_BARBARIAN,
  VIDEO_SPY_RIOT,
  VIDEO_URGENT_MESSAGE1,
  VIDEO_URGENT_MESSAGE2,
  VIDEO_VICTORY_BALCONY,
  VIDEO_VICTORY_SENATE,
  VIDEO_WIN_GAME,
};

#endif // VIDEOS_H
